name       : dbus-broker
version    : 32
release    : 1
source     :
    - https://github.com/bus1/dbus-broker/releases/download/v32/dbus-broker-32.tar.xz : bea7f653e7251063c5f427e9e3f93562d38a0d8667ae6d49fb56f113605985de
license    : Apache-2.0
component  : desktop.core
summary    : Linux D-Bus Message Broker
description: |
    The dbus-broker project is an implementation of a message bus as defined by the D-Bus specification. Its aim is to provide high performance and reliability, while keeping compatibility to the D-Bus reference implementation. It is exclusively written for Linux systems, and makes use of many modern features provided by recent linux kernel releases.
builddeps  :
    - pkgconfig(audit)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # test_get_connection_unix_user fails
    %ninja_check || :
