name       : dbus-broker
version    : 33
release    : 2
source     :
    - https://github.com/bus1/dbus-broker/releases/download/v33/dbus-broker-33.tar.xz : 23713f25624749fdb274907e429080fa2d8f4dbe76acd87bb6d21a3c818c7841
license    : Apache-2.0
component  : desktop.core
summary    : Linux D-Bus Message Broker
description: |
    The dbus-broker project is an implementation of a message bus as defined by the D-Bus specification. Its aim is to provide high performance and reliability, while keeping compatibility to the D-Bus reference implementation. It is exclusively written for Linux systems, and makes use of many modern features provided by recent linux kernel releases.
builddeps  :
    - pkgconfig(audit)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    unset LD_PRELOAD
    %ninja_check
